# AAI614: Data Science & its Applications

*Notebook 2.3: Visualization Using AutoViz*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%202/Notebook2.3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import subprocess
import pkg_resources

required = {'autoviz'}
installed = {pkg.key for pkg in pkg_resources.working_set}
missing = required - installed

if missing:
    python = sys.executable
    subprocess.check_call([python, '-m', 'pip', 'install', *missing], stdout=subprocess.DEVNULL)

import pandas as pd
import numpy as np
from autoviz import AutoViz_Class
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

/tmp/ipykernel_5862/3086438148.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)

In [2]:
AV = AutoViz_Class()

In [3]:
path = ''
filename = 'https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/Boston.csv'
sep = ','
target = 'chas'

In [4]:
df = pd.read_csv(path+filename,sep=sep)
dft = df[:]
print(df.shape)
df.head(1)

(506, 15)

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24.0

In [6]:
df.tail()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [5]:
dft = AV.AutoViz(path+filename, sep, depVar=target, dfte="",
           header=0, verbose=1,
            lowess=False,chart_format='bokeh',max_rows_analyzed=150000,max_cols_analyzed=30)

Shape of your Data Set loaded: (506, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  11
    Number of Integer-Categorical Columns =  2
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    14 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0']

################ Binary_Classification problem #####################

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

Row
    [0] WidgetBox
        [0] Select(label='x', name='x', options=['chas'], value='chas')
        [1] Select(label='y', name='y', options=['crim', 'zn', ...], value='crim')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Row
    [0] WidgetBox
        [0] Select(label='X-Axis', name='X-Axis', options=['crim', 'zn', ...], value='crim')
        [1] Select(label='Y-Axis', name='Y-Axis', options=['crim', 'zn', ...], value='zn')
        [2] Select(label='Color', name='Color', options=['None', 'chas'], value='None')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(label='Select_categorical_var', options=[np.str_('rad'), ...], value=np.str_('rad'))

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(label='Select_numeric_variable', options=[np.str_('lstat'), ...], value=np.str_('lstat'))

KDE plot is erroring due to problems with DynamicMaps. Hence it is skipped

HoloViews(Layout)

No date vars could be found in data set

HoloViews(Overlay, height=800, sizing_mode='fixed', width=1200)

Row
    [0] WidgetBox
        [0] Select(label='X-Axis', name='X-Axis', options=['rad', 'tax', 'chas'], value='rad')
        [1] Select(label='Y-Axis', name='Y-Axis', options=['crim', 'zn', ...], value='crim')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Time to run AutoViz (in seconds) = 26

WARNING:root:Dropping a patch because it contains a previously known reference (id='b2895d94-4cac-4d0d-8cbb-49e289822b2b'). Most of the time this is harmless and usually a result of updating a model on one side of a communications channel while it was being removed on the other end.
WARNING:root:Dropping a patch because it contains a previously known reference (id='b2895d94-4cac-4d0d-8cbb-49e289822b2b'). Most of the time this is harmless and usually a result of updating a model on one side of a communications channel while it was being removed on the other end.
WARNING:root:Dropping a patch because it contains a previously known reference (id='b2895d94-4cac-4d0d-8cbb-49e289822b2b'). Most of the time this is harmless and usually a result of updating a model on one side of a communications channel while it was being removed on the other end.
WARNING:root:Dropping a patch because it contains a previously known reference (id='b2895d94-4cac-4d0d-8cbb-49e289822b2b'). Most of the time this is harmless and usually a result of updating a model on one side of a communications channel while it was being removed on the other end.

In [7]:
target = ''
dft = AV.AutoViz(filename, sep=',', depVar=target, dfte=df)

Shape of your Data Set loaded: (506, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  11
    Number of Integer-Categorical Columns =  2
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  1
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    15 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0']
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Number of All Scatter Plots = 66
All Plots done
Time to run AutoViz = 8 seconds

 ###################### AUTO VISUALIZATION Completed ########################